version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only:
                - main
jobs:
  build:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - run:
          npm run build
