version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          app-name: brg-visualizer-stage
          filters:
            branches:
              only:
                - main
