version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3

workflows:
  node-tests:
    jobs:
      - node/test

  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - node/build
          filters:
            branches:
              only:
                - main
jobs:
  build:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - run:
          npm run build
